### ISSUE TITLE
Yo, are you writing defillama wrapper or something ? 

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [leruaa/defillama-rs#1]
i would contribute on it if so. Please let me know if we can connect

**Comment by leruaa** [comment]
Yes, I need the `/prices/current/{coins}` endpoint at least

**Comment by DoTheBestToGetTheBest** [comment]
> Yes, I need the `/prices/current/{coins}` endpoint at least

if you want i can participate on this library :)

**Comment by leruaa** [comment]
Yes, don't hesitate to create issues about what you want to do so we can discuss :)

Btw I just pushed the `/prices/current/{coins}` endpoint
